[tool.black]
line-length = 100
skip-string-normalization = true

[tool.pyright]
exclude = [
    "**/__pycache__",
    "build",
    "dist",
    "venv",
]
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "error"
pythonVersion = "3.8"
typeCheckingMode = "basic"